shell output improvements

diff --git a/script/install b/script/install
--- a/script/install
+++ b/script/install
@@ -7,32 +7,54 @@ BASH_SOURCES=$(find . -name "*.sh" -type f -exec ls {} \;)
 
 echo ''
 
+info () {
+  echo -e "\e[36m$1\e[0m"
+}
+
+error () {
+  echo -e "\e[31m$1\e[0m"
+}
+
+success () {
+  echo -e "\e[32m$1\e[0m"
+}
+
+warn () {
+  echo -e "\e[33m$1\e[0m"
+}
+
+
 set -e
 
-printf "Setting up bin files...\n"
+info "Setting up bin files..."
 if [ ! -d "$DOTFILES_ROOT/bin" ]; then
   ln -s $DOTFILES_ROOT/bin ~/bin
-  printf "bin files installed successfully\n"
+  success "→ bin files installed successfully"
 else
-  printf "bin files already installed\n"
+  warn "→ bin files already installed"
 fi
 
-printf "running bash install scripts...\n"
+info "Running bash install scripts..."
 for file_name in $BASH_SOURCES; do
   title=`grep '\# title\: ' $file_name | sed -e 's/# title: //g'`
-  printf "→ installing $title ($file_name)...\n"
-  sh $file_name
+  info "Installing $title ($file_name)..."
+  sh $file_name > /dev/null
+  if [ $? -eq 0 ]; then
+    success "→ $title installed successfully"
+  else
+    error "→ $title install failed"
+  fi
 done
 
-printf "symlinking dotfiles...\n"
+info "Symlinking dotfiles..."
 for file_name in $DOTFILES_SOURCES; do
   source_location=$DOTFILES_ROOT/`echo $file_name | sed -e 's/\.\///g'`
   new_location=~/`echo $file_name | sed -e 's/\.\///g' -e 's/\.symlink//g' -e 's/^.*\//./g'`
 
   if [ ! -f $new_location ]; then
     ln -s $source_location $new_location
-    printf "→ done symlinking $new_location...\n"
+    success "→ done symlinking $new_location..."
   else
-    printf "→ skipping symlink for $new_location (already exists)...\n"
+    warn "→ skipping symlink for $new_location (already exists)..."
   fi
 done
